I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 43, in script
    $ game_map = GameMap_Creator(dic)
  File "game/script.rpy", line 43, in <module>
    $ game_map = GameMap_Creator(dic)
  File "game/game_map_datas.rpy", line 86, in __init__
    self.matrix[row][col] = GameMap_ObjLocation( {"obj_type":"None", "pos":[row, col], "explore_point":-1} )
  File "game/game_map_datas.rpy", line 37, in __init__
    self.hot = dic["hot"]
KeyError: u'hot'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 43, in script
    $ game_map = GameMap_Creator(dic)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 43, in <module>
    $ game_map = GameMap_Creator(dic)
  File "game/game_map_datas.rpy", line 86, in __init__
    self.matrix[row][col] = GameMap_ObjLocation( {"obj_type":"None", "pos":[row, col], "explore_point":-1} )
  File "game/game_map_datas.rpy", line 37, in __init__
    self.hot = dic["hot"]
KeyError: u'hot'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
YiZiQianJun 1.0
Wed Jan 01 09:09:44 2020
